# Parameter recovery check: simulate from archer_fit.stan's own generative
# model with known parameters, fit, and see whether the posterior finds them
# again.
#
# This is a different question from the package's testthat suite, which checks
# that the R plumbing builds the right Stan data list. Nothing there says the
# model can identify its own parameters from realistic data, which is what this
# script is for.
#
# Simulated at the Wockner design: same observation grid, same rough number of
# series, same bounds. Recovery on data this model generated itself is a
# necessary condition, not a sufficient one, but failing it would mean
# something is badly wrong.
#
# Runs locally; takes a while (a full fit), so it is not part of the automated
# tests.


suppressPackageStartupMessages({
    library(plasmofit)
    library(tidyverse)
    library(rstan)
    library(posterior)
})

options(mc.cores = min(4L, parallel::detectCores()))


# ------------------------------------------------------------------------ #
# Design
# ------------------------------------------------------------------------ #

# Observation times sampled from Wockner:
ALL_TS <- seq(72, 216, 12)

N_TS <- 64L          # series
N_OBS_EACH <- 8L     # observations per series
N_GRP_INIT <- 2L
N_GRP_R <- 8L
N_GRP_CL <- 8L
N_GRP_SD <- 1L

MIN_CL <- 35
MAX_CL <- 50
MAX_R <- 50
MAX_SHAPE <- 250

SEED_DESIGN <- 2104249041
SEED_TRUTH <- 1333619777
SEED_NOISE <- 831910407
SEED_FIT <- 538065874


# ------------------------------------------------------------------------ #
# Truth
# ------------------------------------------------------------------------ #

set.seed(SEED_DESIGN)

# series-level group assignments
grp_init <- rep(seq_len(N_GRP_INIT), each = N_TS / N_GRP_INIT)
grp_R    <- rep(seq_len(N_GRP_R), N_TS / N_GRP_R)
grp_cl   <- rep(rep(seq_len(N_GRP_CL), each = 2L), N_TS / (2 * N_GRP_CL))
grp_sd   <- rep(1L, N_TS)

ts_by_series <- map(seq_len(N_TS), \(i) sort(sample(ALL_TS, N_OBS_EACH)))

set.seed(SEED_TRUTH)

truth <- local({
    mean_logit_cl <- logit((48 - MIN_CL) / (MAX_CL - MIN_CL))

    b_shape      <- rlnorm(N_GRP_INIT, 2, 0.5)
    b_offset     <- runif(N_GRP_INIT, 0.1, 0.9)
    log10_total0 <- rnorm(N_GRP_INIT, 1, 0.25)

    mu_logit_R     <- rnorm(1, -2, 1)
    sigma_logit_R  <- rtnorm(1, lower = 0, sigma = 1)
    mu_logit_cl    <- rnorm(1, mean_logit_cl, 1)
    sigma_logit_cl <- rtnorm(1, lower = 0, sigma = 0.5)

    list(b_shape = b_shape,
         b_offset = b_offset,
         log10_total0 = log10_total0,
         R = MAX_R * inv_logit(mu_logit_R + rnorm(N_GRP_R) * sigma_logit_R),
         cycle_length = MIN_CL + (MAX_CL - MIN_CL) *
             inv_logit(mu_logit_cl + rnorm(N_GRP_CL) * sigma_logit_cl),
         sd_iRBC = rtnorm(N_GRP_SD, lower = 0, sigma = 0.2))
})

stopifnot(all(truth$cycle_length > MIN_CL), all(truth$cycle_length < MAX_CL))


# ------------------------------------------------------------------------ #
# Simulate observations
# ------------------------------------------------------------------------ #

# Uses the matrix_exp path rather than the series solution, so the simulation
# is not generated by the same code the fit then inverts.
simulate_series <- function(n_c, cycle_length, b_shape, b_offset,
                            log10_total0, R, ts, dt) {
    y0 <- plasmofit:::generate_starts(cycle_length, n_c, b_shape, b_offset,
                                      log10_total0)
    plasmofit:::mat_exp_series(y0 = y0, cycle_length = cycle_length, n_c = n_c,
                               R = R, mu = 0, ts = ts, dt = dt)
}

N_C <- 96L
DT <- 12

y_true <- map(seq_len(N_TS), \(i) {
    simulate_series(N_C,
                    truth$cycle_length[grp_cl[i]],
                    truth$b_shape[grp_init[i]],
                    truth$b_offset[grp_init[i]],
                    truth$log10_total0[grp_init[i]],
                    truth$R[grp_R[i]],
                    ts_by_series[[i]], DT)
})

set.seed(SEED_NOISE)

sim_df <- tibble(
    id    = rep(sprintf("s%03d", seq_len(N_TS)), each = N_OBS_EACH),
    time  = list_c(ts_by_series),
    y_true = list_c(y_true),
    inoc  = rep(sprintf("i%d", grp_init), each = N_OBS_EACH),
    trial = rep(sprintf("t%d", grp_R), each = N_OBS_EACH),
    cl_grp = rep(sprintf("c%d", grp_cl), each = N_OBS_EACH),
    oe    = rep(sprintf("e%d", grp_sd), each = N_OBS_EACH)
) |>
    # observation error is on the log10(1 + y) scale, matching the likelihood
    mutate(para = pmax(0, 10^(log10(y_true + 1) +
                                  rnorm(n(), 0, truth$sd_iRBC[1])) - 1))


# ------------------------------------------------------------------------ #
# Fit
# ------------------------------------------------------------------------ #

d <- archer_stan_data(sim_df,
                      series = "id", time = "time", abundance = "para",
                      grp_init = "inoc", grp_R = "trial", grp_cl = "cl_grp",
                      grp_sd = "oe",
                      n_c = N_C, min_cl = MIN_CL, max_cl = MAX_CL,
                      max_R = MAX_R, max_shape = MAX_SHAPE,
                      calc_log_lik = 0L)

# The truth vectors are indexed by the simulation's own group numbering, while
# archer_stan_data() recodes groups by order of first appearance. They agree
# for this design, but check rather than assume: a silent mismatch here would
# look exactly like a recovery failure.
lv <- attr(d, "levels")
stopifnot(identical(lv$inoc,   sprintf("i%d", sort(unique(grp_init)))),
          identical(lv$trial,  sprintf("t%d", sort(unique(grp_R)))),
          identical(lv$cl_grp, sprintf("c%d", sort(unique(grp_cl)))))

fit <- archer_fit(d, chains = 4L, iter = 1700L, warmup = 700L, seed = SEED_FIT)

write_rds(list(fit = fit, data = d, truth = truth, sim_df = sim_df),
          "_data/test-archer-fit.rds")


# ------------------------------------------------------------------------ #
# Sampler health first: recovery numbers mean nothing if it did not converge
# ------------------------------------------------------------------------ #

par_names <- c("b_shape", "b_offset", "R", "log10_total0", "cycle_length",
               "sd_iRBC")

diags <- map(par_names, \(p) {
    sims <- rstan::extract(fit, p, permuted = FALSE)
    tibble(par = dimnames(sims)$parameters,
           rhat = apply(sims, 3, posterior::rhat),
           ess_bulk = apply(sims, 3, posterior::ess_bulk),
           ess_tail = apply(sims, 3, posterior::ess_tail))
}) |> list_rbind()

cat("=== sampler ===\n")
cat("  divergences:", sum(rstan::get_divergent_iterations(fit)), "\n")
cat("  max R-hat:  ", round(max(diags$rhat, na.rm = TRUE), 4), "\n")
cat("  min ESS:    ", round(min(diags$ess_bulk, na.rm = TRUE)), "\n")
lp <- rstan::extract(fit, "lp__", permuted = FALSE)
cat("  lp by chain:", paste(round(apply(lp, 2, mean), 1), collapse = "  "), "\n")


# ------------------------------------------------------------------------ #
# Recovery
# ------------------------------------------------------------------------ #

# z: how many posterior SDs the truth sits from the posterior mean. |z| under
# about 2 is unremarkable; consistently large |z| means bias, not noise.
# covered: whether the 95% credible interval contains the truth. Across many
# parameters that should happen about 95% of the time.
recovery <- map(par_names, \(p) {
    post <- as.matrix(fit, pars = p)
    tv <- truth[[p]]
    stopifnot(length(tv) == ncol(post))
    tibble(par = colnames(post),
           truth = tv,
           mean = colMeans(post),
           sd = apply(post, 2, sd),
           lo = apply(post, 2, quantile, 0.025),
           hi = apply(post, 2, quantile, 0.975)) |>
        mutate(z = (mean - truth) / sd,
               covered = truth >= lo & truth <= hi)
}) |> list_rbind()

cat("\n=== recovery ===\n")
recovery |>
    mutate(across(c(truth, mean, sd, lo, hi, z), \(x) round(x, 3))) |>
    print(n = Inf)

cat(sprintf("\n  95%% intervals covering truth: %d/%d (%.0f%%)\n",
            sum(recovery$covered), nrow(recovery),
            100 * mean(recovery$covered)))
cat(sprintf("  max |z|: %.2f (%s)\n", max(abs(recovery$z)),
            recovery$par[which.max(abs(recovery$z))]))

by_par <- recovery |>
    mutate(grp = sub("[[].*", "", par)) |>
    summarize(n = n(), covered = sum(covered), max_abs_z = max(abs(z)),
              .by = grp)
cat("\n  by parameter:\n")
print(by_par)

if (mean(recovery$covered) < 0.8) {
    warning("coverage well below nominal; check the sampler diagnostics above ",
            "before concluding the model cannot recover its parameters")
}
